name: Deploy Theme
on:
 push:
  branches: [master]
env:
    SSH_USER: ${{ secrets.SSH_USER }}
    SSH_HOST: ${{ secrets.SSH_HOST }}
jobs:
   deploy:
     name: Deploy WordPress Theme on GoDaddy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Deploy to GoDaddy
         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
         with: 
           server: ftp.wattbridge.info
           username: ${{ secrets.PE_FTP_UN }}
           password: ${{ secrets.PE_FTP_PW }}
           local-dir: devproroot/wp-content/themes/proenergy
